[book]
authors = [
  "Maja Mataric",
  "Ross Mead",
  "Mark Yim",
  "Simon Kim",
  "Andrew Specian",
  "Braden McDorman",
]
language = "en"
src = "src"
title = "Quori v1 Documentation"

[output.html]

[output.linkcheck]
